"""Domain services for accounts application.

Owns:
- Device credentials generation, rotation, revocation
- Device session creation and enforcement
- User/role management operations
- Installation first-run initialization
"""

from django.core.exceptions import ValidationError
from django.db import transaction
from accounts.models import Role, User
from accounts.selectors import is_installation_initialized


import secrets
from typing import Any, Optional, Tuple
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils import timezone
from accounts.models import CredentialStatus, Device, DeviceSession, DeviceType, Role, User
from accounts.selectors import get_active_device_session, is_installation_initialized


def generate_secure_password(length: int = 14) -> str:
    """Generate a high-entropy, cryptographically secure random password."""
    return secrets.token_urlsafe(length)


def initialize_installation(username: str, email: str, password: str) -> User:
    """Create the single human Administrator account during first-run setup.
    
    Transitions installation state from UNINITIALIZED -> INITIALIZED.
    Raises ValidationError if the installation is already initialized.
    """
    with transaction.atomic():
        if is_installation_initialized():
            raise ValidationError(
                "Installation is already initialized. Only one Administrator account is permitted."
            )

        admin_user = User.objects.create_user(
            username=username,
            email=email,
            password=password,
            role=Role.ADMIN,
            is_staff=True,
            is_superuser=True,
        )
        return admin_user


def create_device(
    identifier: str,
    device_type: str,
    initial_password: Optional[str] = None,
    booth: Optional[Any] = None,
) -> Tuple[Device, str]:
    """Provision a new technical device identity with autogenerated credentials.
    
    Returns (Device, plain_password).
    """
    if device_type not in (DeviceType.OFFICER, DeviceType.KIOSK):
        raise ValidationError(f"Invalid device type: {device_type}")

    if initial_password is None:
        initial_password = generate_secure_password()

    with transaction.atomic():
        if Device.objects.filter(identifier=identifier).exists():
            raise ValidationError(f"Device with identifier '{identifier}' already exists.")

        role = Role.OFFICER if device_type == DeviceType.OFFICER else Role.KIOSK
        user = User.objects.create_user(
            username=identifier,
            password=initial_password,
            role=role,
            is_staff=False,
            is_superuser=False
        )

        device = Device.objects.create(
            user=user,
            identifier=identifier,
            device_type=device_type,
            booth=booth,
            credential_status=CredentialStatus.ACTIVE,
            credential_version=1,
            last_rotated_at=timezone.now()
        )
        return device, initial_password



def rotate_device_credentials(device_id: int) -> Tuple[Device, str]:
    """Rotate credentials for a device: generates a new password and invalidates active sessions.
    
    Returns (Device, new_plain_password).
    """
    new_password = generate_secure_password()
    with transaction.atomic():
        device = Device.objects.select_for_update().get(id=device_id)
        user = device.user

        # Update password securely
        user.set_password(new_password)
        user.save()

        # Update device rotation tracking
        device.credential_version += 1
        device.last_rotated_at = timezone.now()
        device.credential_status = CredentialStatus.ACTIVE
        device.save()

        # Invalidate any active session immediately
        DeviceSession.objects.filter(device=device, is_active=True).update(
            is_active=False,
            revoked_at=timezone.now()
        )

        return device, new_password


def revoke_device_credentials(device_id: int) -> Device:
    """Revoke credentials for a device and terminate any active session."""
    with transaction.atomic():
        device = Device.objects.select_for_update().get(id=device_id)
        device.credential_status = CredentialStatus.REVOKED
        device.save()

        DeviceSession.objects.filter(device=device, is_active=True).update(
            is_active=False,
            revoked_at=timezone.now()
        )
        return device


def create_device_session(device: Device, session_key: str) -> DeviceSession:
    """Establish an active session for a Device, enforcing single-active-session invariant."""
    with transaction.atomic():
        locked_device = Device.objects.select_for_update().get(id=device.id)

        if locked_device.credential_status != CredentialStatus.ACTIVE:
            raise ValidationError("Device credentials are not active.")

        active_session = DeviceSession.objects.filter(device=locked_device, is_active=True).first()
        if active_session:
            raise ValidationError(
                f"Device '{locked_device.identifier}' already has an active session. Simultaneous sessions are prohibited."
            )

        session = DeviceSession.objects.create(
            device=locked_device,
            session_key=session_key,
            is_active=True
        )
        return session


def terminate_device_session(session_key: str) -> None:
    """Terminate an active device session."""
    with transaction.atomic():
        DeviceSession.objects.filter(session_key=session_key, is_active=True).update(
            is_active=False,
            revoked_at=timezone.now()
        )


def login_device_user(request, user: User) -> None:
    """Authenticate and log in a User, enforcing one active session for devices."""
    if user.role == Role.ADMIN:
        login(request, user)
        return

    # For technical device identities (OFFICER, KIOSK)
    try:
        device = user.device
    except (AttributeError, Device.DoesNotExist):
        raise ValidationError("No associated device found for this identity.")

    if device.credential_status != CredentialStatus.ACTIVE:
        raise ValidationError("Device credentials have been revoked. Contact the Administrator.")

    with transaction.atomic():
        locked_device = Device.objects.select_for_update().get(id=device.id)
        if locked_device.credential_status != CredentialStatus.ACTIVE:
            raise ValidationError("Device credentials have been revoked.")

        active_session = DeviceSession.objects.filter(device=locked_device, is_active=True).first()
        if active_session:
            raise ValidationError(
                f"Device '{locked_device.identifier}' already has an active session. Simultaneous sessions are prohibited."
            )

        # Login with Django session
        login(request, user)
        if not request.session.session_key:
            request.session.save()

        DeviceSession.objects.create(
            device=locked_device,
            session_key=request.session.session_key,
            is_active=True
        )


def logout_user(request) -> None:
    """Log out user and terminate any associated active device session."""
    if request.user.is_authenticated and hasattr(request.user, 'device'):
        if request.session.session_key:
            terminate_device_session(request.session.session_key)
    logout(request)

