"""Domain services for accounts application.

Owns:
- Device credentials generation, rotation, revocation
- Device session creation and enforcement
- User/role management operations
- Installation first-run initialization
"""

from django.core.exceptions import ValidationError
from django.db import transaction
from accounts.models import Role, User
from accounts.selectors import is_installation_initialized


import secrets
from typing import Any, Optional, Tuple
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils import timezone
from accounts.models import CredentialStatus, Device, DeviceSession, DeviceType, Role, User
from accounts.selectors import get_active_device_session, is_installation_initialized


READABLE_WORDS = [
    'amber', 'cedar', 'delta', 'eagle', 'falcon', 'harbor', 'island', 'jupiter',
    'maple', 'nexus', 'orbit', 'pacific', 'quartz', 'river', 'summit', 'tiger',
    'valley', 'zenith', 'beacon', 'canyon', 'forest', 'meadow', 'shadow', 'silver',
    'aurora', 'blaze', 'coral', 'drift', 'glade', 'haven', 'lagoon', 'oasis',
    'prism', 'ridge', 'sierra', 'tundra', 'vortex', 'willow', 'zephyr', 'zen'
]


def generate_secure_readable_password() -> str:
    """Generate a high-entropy, human-readable secure password (e.g. Falcon-482-River).
    
    Easily communicated and typed by station poll workers while maintaining strong cryptographic entropy.
    """
    w1 = secrets.choice(READABLE_WORDS).capitalize()
    w2 = secrets.choice(READABLE_WORDS).capitalize()
    num = secrets.randbelow(900) + 100  # 100-999
    return f"{w1}-{num}-{w2}"


def generate_secure_password(length: int = 14) -> str:
    """Generate a high-entropy, human-readable secure password."""
    return generate_secure_readable_password()


def initialize_installation(username: str, email: str, password: str) -> User:
    """Create the single human Administrator account during first-run setup.
    
    Transitions installation state from UNINITIALIZED -> INITIALIZED.
    Raises ValidationError if the installation is already initialized.
    """
    with transaction.atomic():
        if is_installation_initialized():
            raise ValidationError(
                "Installation is already initialized. Only one Administrator account is permitted."
            )

        admin_user = User.objects.create_user(
            username=username,
            email=email,
            password=password,
            role=Role.ADMIN,
            is_staff=True,
            is_superuser=True,
        )
        return admin_user


def cleanup_past_credentials() -> int:
    """Automatically remove station device credentials (User and Device records)
    that belong to a booth whose election is no longer in draft or active status.
    """
    from elections.models import Election, ElectionStatus

    active_or_draft_election_ids = Election.objects.filter(
        status__in=[ElectionStatus.DRAFT, ElectionStatus.ACTIVE]
    ).values_list("id", flat=True)

    # Station devices that belong to an election that is NOT draft or active (e.g. CLOSED)
    stale_devices = Device.objects.filter(
        booth__isnull=False
    ).exclude(
        booth__election_id__in=active_or_draft_election_ids
    )
    stale_user_ids = set(stale_devices.values_list("user_id", flat=True))

    deleted_count = 0
    if stale_user_ids:
        # Invalidate any active sessions for stale devices
        DeviceSession.objects.filter(device__user_id__in=stale_user_ids).delete()
        Device.objects.filter(user_id__in=stale_user_ids).delete()
        deleted_count, _ = User.objects.filter(id__in=stale_user_ids).delete()
    return deleted_count


def create_device(
    identifier: str,
    device_type: str,
    initial_password: Optional[str] = None,
    booth: Optional[Any] = None,
) -> Tuple[Device, str]:
    """Provision a new technical device identity with autogenerated readable credentials.
    
    Returns (Device, plain_password).
    """
    if device_type not in (DeviceType.OFFICER, DeviceType.KIOSK):
        raise ValidationError(f"Invalid device type: {device_type}")

    if initial_password is None:
        initial_password = generate_secure_readable_password()

    with transaction.atomic():
        # First ensure past unused station credentials are swept away
        cleanup_past_credentials()

        # If an orphan user with this username still exists, remove it
        orphan = User.objects.filter(username=identifier, role__in=[Role.OFFICER, Role.KIOSK]).first()
        if orphan and (not hasattr(orphan, "device") or orphan.device.booth is None):
            orphan.delete()

        if Device.objects.filter(identifier=identifier).exists() or User.objects.filter(username=identifier).exists():
            raise ValidationError(f"Device with identifier '{identifier}' already exists.")

        role = Role.OFFICER if device_type == DeviceType.OFFICER else Role.KIOSK
        user = User.objects.create_user(
            username=identifier,
            password=initial_password,
            role=role,
            is_staff=False,
            is_superuser=False
        )

        device = Device.objects.create(
            user=user,
            identifier=identifier,
            device_type=device_type,
            booth=booth,
            cleartext_password=initial_password,
            credential_status=CredentialStatus.ACTIVE,
            credential_version=1,
            last_rotated_at=timezone.now()
        )
        return device, initial_password



def rotate_device_credentials(device_id: int) -> Tuple[Device, str]:
    """Rotate credentials for a device: generates a new readable password, updates cleartext_password, and invalidates active sessions.
    
    Returns (Device, new_plain_password).
    """
    new_password = generate_secure_readable_password()
    with transaction.atomic():
        device = Device.objects.select_for_update().get(id=device_id)
        user = device.user

        # Update password securely
        user.set_password(new_password)
        user.save()

        # Update device rotation tracking & stored readable password
        device.credential_version += 1
        device.cleartext_password = new_password
        device.last_rotated_at = timezone.now()
        device.credential_status = CredentialStatus.ACTIVE
        device.save()

        # Invalidate any active session immediately
        DeviceSession.objects.filter(device=device, is_active=True).update(
            is_active=False,
            revoked_at=timezone.now()
        )

        return device, new_password


def revoke_device_credentials(device_id: int) -> Device:
    """Revoke credentials for a device and terminate any active session."""
    with transaction.atomic():
        device = Device.objects.select_for_update().get(id=device_id)
        device.credential_status = CredentialStatus.REVOKED
        device.save()

        DeviceSession.objects.filter(device=device, is_active=True).update(
            is_active=False,
            revoked_at=timezone.now()
        )
        return device


def create_device_session(device: Device, session_key: str) -> DeviceSession:
    """Establish an active session for a Device, enforcing single-active-session invariant."""
    with transaction.atomic():
        locked_device = Device.objects.select_for_update().get(id=device.id)

        if locked_device.credential_status != CredentialStatus.ACTIVE:
            raise ValidationError("Device credentials are not active.")

        active_session = DeviceSession.objects.filter(device=locked_device, is_active=True).first()
        if active_session:
            raise ValidationError(
                f"Device '{locked_device.identifier}' already has an active session. Simultaneous sessions are prohibited."
            )

        session = DeviceSession.objects.create(
            device=locked_device,
            session_key=session_key,
            is_active=True
        )
        return session


def terminate_device_session(session_key: str) -> None:
    """Terminate an active device session."""
    with transaction.atomic():
        DeviceSession.objects.filter(session_key=session_key, is_active=True).update(
            is_active=False,
            revoked_at=timezone.now()
        )


def login_device_user(request, user: User) -> None:
    """Authenticate and log in a User, enforcing one active session for devices."""
    if user.role == Role.ADMIN:
        login(request, user)
        return

    # For technical device identities (OFFICER, KIOSK)
    try:
        device = user.device
    except (AttributeError, Device.DoesNotExist):
        raise ValidationError("No associated device found for this identity.")

    if device.credential_status != CredentialStatus.ACTIVE:
        raise ValidationError("Device credentials have been revoked. Contact the Administrator.")

    booth = getattr(device, "booth", None)
    if booth and getattr(booth, "election", None):
        from elections.models import ElectionStatus
        if booth.election.status not in (ElectionStatus.DRAFT, ElectionStatus.ACTIVE):
            raise ValidationError("Officer credentials are only valid for draft or active elections.")

    with transaction.atomic():
        locked_device = Device.objects.select_for_update().get(id=device.id)
        if locked_device.credential_status != CredentialStatus.ACTIVE:
            raise ValidationError("Device credentials have been revoked.")

        active_session = DeviceSession.objects.filter(device=locked_device, is_active=True).first()
        if active_session:
            raise ValidationError(
                f"Device '{locked_device.identifier}' already has an active session. Simultaneous sessions are prohibited."
            )

        # Login with Django session
        login(request, user)
        if not request.session.session_key:
            request.session.save()

        DeviceSession.objects.create(
            device=locked_device,
            session_key=request.session.session_key,
            is_active=True
        )


def logout_user(request) -> None:
    """Log out user and terminate any associated active device session."""
    if request.user.is_authenticated and hasattr(request.user, 'device'):
        if request.session.session_key:
            terminate_device_session(request.session.session_key)
    logout(request)


def get_post_login_redirect_url(user: User) -> str:
    """Return the canonical role-based dashboard destination URL."""
    from django.urls import reverse
    if getattr(user, "role", None) == Role.ADMIN:
        return reverse("elections:dashboard")
    elif getattr(user, "role", None) == Role.OFFICER:
        return reverse("voting:officer_dashboard")
    elif getattr(user, "role", None) == Role.KIOSK:
        return reverse("voting:kiosk")
    return reverse("index")


