/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './templates/**/*.html',
    './accounts/templates/**/*.html',
    './elections/templates/**/*.html',
    './voters/templates/**/*.html',
    './voting/templates/**/*.html',
    './static/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        electra: {
          page: '#F8F9FA',
          surface: '#FFFFFF',
          'surface-subtle': '#F9FAFB',
          'surface-hover': '#F3F4F6',
          border: '#E5E7EB',
          'border-subtle': '#F0F2F5',
          primary: '#0D6EFD',
          'primary-hover': '#0B5ED7',
          'primary-soft': '#EFF6FF',
          'primary-active-bg': '#CFE4FE',
          'primary-active-text': '#1D4ED8',
          dark: '#111827',
          black: '#000000',
          gray: '#4B5563',
          'gray-light': '#6B7280',
          muted: '#9CA3AF',
          green: '#00BA66',
          'green-soft': '#E6F8F0',
          orange: '#FFA000',
          'orange-soft': '#FFF5E5',
          coral: '#FA5A38',
          'coral-soft': '#FEEFEA',
          blue: '#1677E8',
          'blue-soft': '#EBF3FD',
        },
      },
      borderRadius: {
        card: '20px',
        inner: '14px',
        pill: '9999px',
        btn: '10px',
        badge: '6px',
        nav: '8px',
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      boxShadow: {
        card: '0 1px 3px rgba(0, 0, 0, 0.04), 0 2px 8px rgba(0, 0, 0, 0.02)',
        floating: '0 10px 30px rgba(0, 0, 0, 0.06)',
        glass: '0 8px 32px rgba(0, 0, 0, 0.12)',
      },
    },
  },
  plugins: [],
};
