# Generated by Django 6.0.8 on 2026-10-02 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0002_candidate_academic_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the group (e.g. Computer Science, Class 10A, Semester 1).', max_length=150)),
                ('type', models.CharField(choices=[('CLASS', 'Class'), ('SECTION', 'Section'), ('DEPARTMENT', 'Department'), ('PROGRAM', 'Program'), ('SEMESTER', 'Semester'), ('COHORT', 'Cohort'), ('OTHER', 'Other')], default='DEPARTMENT', help_text='Structural classification.', max_length=50)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent node in hierarchy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='voters.academicgroup')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_registry_value', models.CharField(help_text='Configured institution-defined identifier (e.g. Student ID, University ID, Admission Number).', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Voter full legal or school name.', max_length=200)),
                ('gender', models.CharField(blank=True, help_text='Gender classification used for eligibility filtering.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_group', models.ForeignKey(blank=True, help_text='Primary department, class, or cohort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='voters.academicgroup')),
            ],
            options={
                'ordering': ['primary_registry_value', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElectionVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_voted', models.BooleanField(default=False, help_text='True once a complete ballot is successfully committed.')),
                ('election', models.ForeignKey(help_text='Parent election.', on_delete=django.db.models.deletion.CASCADE, related_name='election_voters', to='elections.election')),
                ('voter', models.ForeignKey(help_text='Enrolled voter.', on_delete=django.db.models.deletion.CASCADE, related_name='election_enrollments', to='voters.voter')),
            ],
            options={
                'ordering': ['voter__primary_registry_value', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicgroup',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'parent'), name='unique_academic_group_hierarchy'),
        ),
        migrations.AddConstraint(
            model_name='electionvoter',
            constraint=models.UniqueConstraint(fields=('election', 'voter'), name='unique_voter_per_election'),
        ),
    ]
