# Generated by Django 6.0.8 on 2026-10-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_candidate_academic_group_and_more'),
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.PositiveIntegerField(help_text='Sequential booth number within the election (e.g. 1, 2, 3).')),
                ('name', models.CharField(blank=True, default='', help_text='Optional custom name or room location (e.g. Room 101, Main Auditorium).', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(help_text='Election this booth is configured for.', on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='elections.election')),
            ],
            options={
                'ordering': ['booth_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='electionvoter',
            name='booth',
            field=models.ForeignKey(blank=True, help_text='Assigned physical polling booth.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_voters', to='voters.booth'),
        ),
        migrations.AddConstraint(
            model_name='booth',
            constraint=models.UniqueConstraint(fields=('election', 'booth_number'), name='unique_booth_number_per_election'),
        ),
    ]
