# Generated by Django 6.0.8 on 2026-10-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_booth_electionvoter_booth_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicgroup',
            name='unique_academic_group_hierarchy',
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='name',
            field=models.CharField(help_text='Name of the group (e.g. Computer Science) or sub group (e.g. Batch A).', max_length=150),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent GROUP for sub-groups. NULL for top-level groups.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='voters.academicgroup'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='type',
            field=models.CharField(choices=[('GROUP', 'Group'), ('SUBGROUP', 'Sub Group')], default='GROUP', help_text='GROUP = top-level; SUBGROUP = child of a GROUP.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='academicgroup',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_academic_group_hierarchy'),
        ),
    ]
