# Generated by Django 6.0.8 on 2026-10-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_remove_academicgroup_unique_academic_group_hierarchy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the registry (e.g. CET Students, Faculty & Staff).', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this registry.')),
                ('primary_id_source', models.CharField(default='Student ID', help_text='Source column mapped to Primary Identifier (e.g. Student ID, Employee ID).', max_length=100)),
                ('name_source', models.CharField(default='Name', help_text='Source column mapped to Name (e.g. Name, Full Name).', max_length=100)),
                ('group_source', models.CharField(default='Department', help_text='Source column mapped to Group (e.g. Department, Class).', max_length=100)),
                ('subgroup_source', models.CharField(default='Semester', help_text='Source column mapped to Sub-group (e.g. Semester, Batch, Designation).', max_length=100)),
                ('gender_source', models.CharField(default='Gender', help_text='Source column mapped to Gender.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='academicgroup',
            name='unique_academic_group_hierarchy',
        ),
        migrations.AlterField(
            model_name='voter',
            name='primary_registry_value',
            field=models.CharField(help_text='Configured institution-defined identifier (e.g. Student ID, University ID, Admission Number).', max_length=100),
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='registry',
            field=models.ForeignKey(blank=True, help_text='Voter registry this group belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='voters.voterregistry'),
        ),
        migrations.AddField(
            model_name='voter',
            name='registry',
            field=models.ForeignKey(blank=True, help_text='Voter registry this voter belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.voterregistry'),
        ),
        migrations.AddConstraint(
            model_name='academicgroup',
            constraint=models.UniqueConstraint(fields=('registry', 'name', 'parent'), name='unique_academic_group_hierarchy'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=('registry', 'primary_registry_value'), name='unique_voter_primary_id_per_registry'),
        ),
    ]
