# Generated by Django 6.0.8 on 2026-10-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_populate_initial_registry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterregistry',
            name='description',
        ),
    ]
