# Generated by Django 6.0.8 on 2026-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0006_remove_voterregistry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterregistry',
            name='gender_source',
            field=models.CharField(blank=True, default='Gender', help_text='Source column mapped to Gender.', max_length=100),
        ),
        migrations.AlterField(
            model_name='voterregistry',
            name='subgroup_source',
            field=models.CharField(blank=True, default='Semester', help_text='Source column mapped to Sub-group (e.g. Semester, Batch, Designation).', max_length=100),
        ),
    ]
