# Generated by Django 6.0.8 on 2026-10-02 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Election title.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Institutional overview or notes.')),
                ('starts_at', models.DateTimeField(help_text='Scheduled voting start time.')),
                ('ends_at', models.DateTimeField(help_text='Scheduled voting cutoff time.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('RESULTS_PUBLISHED', 'Results Published')], default='DRAFT', help_text='Canonical lifecycle state.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('results_published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. President, Vice President', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Presentation order on the voting kiosk ballot.')),
                ('election', models.ForeignKey(help_text='Parent election.', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elections.election')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Candidate full name.', max_length=200)),
                ('symbol', models.CharField(blank=True, help_text='Ballot symbol or slate/party name.', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Candidate photo displayed on kiosk.', null=True, upload_to='candidates/')),
                ('position', models.ForeignKey(help_text='Position this candidate is contesting.', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.position')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('election', 'name'), name='unique_position_name_per_election'),
        ),
    ]
