# Generated by Django 6.0.8 on 2026-10-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='academic_group',
            field=models.CharField(blank=True, help_text='Academic department, grade, class, or cohort details.', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('election', 'display_order'), name='unique_position_order_per_election'),
        ),
    ]
