# Generated by Django 6.0.8 on 2026-10-02 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_candidate_academic_group_and_more'),
        ('voters', '0002_booth_electionvoter_booth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='voter',
            field=models.ForeignKey(blank=True, help_text='Optional link to central voter registry identity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidacies', to='voters.voter'),
        ),
        migrations.AlterField(
            model_name='election',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled voting cutoff time.', null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled voting start time (automatically stamped when election goes live).', null=True),
        ),
    ]
