# Generated by Django 6.0.8 on 2026-10-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_election_options_candidate_voter_and_more'),
        ('voters', '0004_voterregistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='voter_registry',
            field=models.ForeignKey(blank=True, help_text='The single voter registry selected as the voter source for this election.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='voters.voterregistry'),
        ),
    ]
