# Generated by Django 6.0.8 on 2026-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_election_voter_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='setup_stage',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current stage in the 4-step setup workflow (1 to 4).'),
        ),
    ]
