# Generated by Django 6.0.8 on 2026-10-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_election_setup_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_saved_draft',
            field=models.BooleanField(default=False, help_text='True if administrator explicitly saved this election draft.'),
        ),
    ]
