# Generated by Django 6.0.8 on 2026-10-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_election_is_saved_draft'),
        ('voters', '0007_alter_voterregistry_gender_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='symbol_image',
            field=models.ImageField(blank=True, help_text='Candidate symbol image (optional).', null=True, upload_to='candidates/symbols/'),
        ),
        migrations.AddField(
            model_name='position',
            name='eligible_groups',
            field=models.ManyToManyField(blank=True, help_text='Specific academic groups eligible to vote for this position. If empty, all voters are eligible.', related_name='positions', to='voters.academicgroup'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, help_text='Candidate photo displayed on kiosk (optional).', null=True, upload_to='candidates/'),
        ),
    ]
