# Generated by Django 6.0.8 on 2026-10-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_candidate_symbol_image_position_eligible_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='eligible_gender',
            field=models.CharField(blank=True, choices=[('ALL', 'All'), ('FEMALE', 'Female'), ('MALE', 'Male')], default='ALL', help_text="Gender restriction for voters eligible to vote for this position. If 'ALL', all genders are eligible.", max_length=20),
        ),
    ]
