# Generated by Django 6.0.8 on 2026-10-02 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Stable logical device identifier (e.g. booth-1-officer, booth-1-kiosk).', max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('OFFICER', 'Officer Station'), ('KIOSK', 'Voting Kiosk')], help_text='Type of station device.', max_length=10)),
                ('credential_status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', help_text='Status of credentials (ACTIVE or REVOKED).', max_length=10)),
                ('credential_version', models.PositiveIntegerField(default=1, help_text='Incremented on each credential rotation.')),
                ('last_rotated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when credentials were last generated or rotated.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Underlying authentication identity.', on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Django session key.', max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.device')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device',), name='unique_active_session_per_device')],
            },
        ),
    ]
