# Generated by Django 6.0.8 on 2026-10-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_device_devicesession'),
        ('voters', '0002_booth_electionvoter_booth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='booth',
            field=models.ForeignKey(blank=True, help_text='Physical booth this device is bound to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='voters.booth'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('booth__isnull', False)), fields=('booth', 'device_type'), name='unique_device_per_booth'),
        ),
    ]
