# Generated by Django 6.0.8 on 2026-10-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_device_booth_device_unique_device_per_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cleartext_password',
            field=models.CharField(blank=True, default='', help_text='Stored readable password for station booth operators.', max_length=128),
        ),
    ]
