# Generated by Django 6.0.8 on 2026-10-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_device_cleartext_password'),
        ('elections', '0008_position_eligible_gender'),
        ('voters', '0007_alter_voterregistry_gender_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the ballot was committed.')),
                ('candidate', models.ForeignKey(help_text='Candidate selected by the voter.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate')),
                ('election', models.ForeignKey(help_text='Election for which this vote was cast.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoterAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Current state of the authorization.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the authorization was created.')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when the ballot was successfully committed.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when the authorization was cancelled by officer or election close.', null=True)),
                ('booth', models.ForeignKey(help_text='Polling booth where this authorization was issued.', on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='voters.booth')),
                ('election_voter', models.ForeignKey(help_text='Enrolled election voter being authorized.', on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='voters.electionvoter')),
                ('kiosk', models.ForeignKey(help_text='Target Voting Kiosk unlocked by this authorization.', on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='accounts.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('election_voter',), name='unique_active_authorization_per_voter'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('kiosk',), name='unique_active_authorization_per_kiosk')],
            },
        ),
    ]
